Repository mesh-adaptation/goalie, pull requests merged in 2024-04, with the labels that each got.

#56 Rework `enforce_element_constraints`
  goalie/metric.py
  test/test_metric.py
  test/test_metric_utils.py
Labels: refactor

#149 146 function data steady label
  goalie/function_data.py
  test/test_function_data.py
Labels: bug

#151 Fix `num_iterations` option usage
  goalie/options.py
Labels: bug, PRIORITY

#159 Link ODE demo into others
  demos/mesh_seq.py
  demos/ode.py
Labels: documentation

#161 Port interpolation functionality to Animate
  .github/workflows/test_suite.yml
  goalie/__init__.py
  goalie/adjoint.py
  goalie/interpolation.py
  goalie/mesh_seq.py
  goalie/utility.py
  test/test_interpolation.py
  test/test_metric.py
  test/test_utility.py
  test_adjoint/test_adjoint.py
  test_adjoint/test_demos.py
  test_adjoint/test_mesh_seq.py
Labels: port, PRIORITY

#163 Drop temporary hack
  test_adjoint/test_demos.py
Labels: bug

#166 Use ruff linter and formatter
  .flake8
  .pre-commit-config.yaml
  Makefile
  README.md
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/mesh_seq.py
  demos/ode.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  demos/solid_body_rotation_split.py
  goalie/adjoint.py
  goalie/error_estimation.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/interpolation.py
  goalie/log.py
  goalie/math.py
  goalie/mesh_seq.py
  goalie/metric.py
  goalie/options.py
  goalie/point_seq.py
  goalie/time_partition.py
  goalie/utility.py
  goalie_adjoint/__init__.py
  pyproject.toml
  test/conftest.py
  test/sensors.py
  test/test_error_estimation.py
  test/test_function_data.py
  test/test_interpolation.py
  test/test_math.py
  test/test_mesh_seq.py
  test/test_metric.py
  test/test_options.py
  test/test_time_partition.py
  test/test_utility.py
  test/utility.py
  test_adjoint/conftest.py
  test_adjoint/examples/burgers.py
  test_adjoint/examples/point_discharge2d.py
  test_adjoint/examples/point_discharge3d.py
  test_adjoint/examples/steady_flow_past_cyl.py
  test_adjoint/test_adjoint.py
  test_adjoint/test_demos.py
  test_adjoint/test_fp_iteration.py
  test_adjoint/test_mesh_seq.py
  test_adjoint/test_utils.py
Labels: optimisation, clarity

#158 Defer to the wiki for installation instructions
  README.md
Labels: documentation, install, clarity

#155 Expand `pyproject`
  .flake8
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/mesh_seq.py
  demos/ode.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  demos/solid_body_rotation_split.py
  goalie/adjoint.py
  goalie/error_estimation.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/log.py
  goalie/math.py
  goalie/mesh_seq.py
  goalie/metric.py
  goalie/options.py
  goalie/point_seq.py
  goalie/time_partition.py
  goalie/utility.py
  goalie_adjoint/__init__.py
  pyproject.toml
  requirements.txt
  setup.py
  test/conftest.py
  test/sensors.py
  test/test_error_estimation.py
  test/test_function_data.py
  test/test_math.py
  test/test_mesh_seq.py
  test/test_metric.py
  test/test_options.py
  test/test_time_partition.py
  test/test_utility.py
  test/utility.py
  test_adjoint/conftest.py
  test_adjoint/examples/burgers.py
  test_adjoint/examples/point_discharge2d.py
  test_adjoint/examples/point_discharge3d.py
  test_adjoint/examples/steady_flow_past_cyl.py
  test_adjoint/test_adjoint.py
  test_adjoint/test_demos.py
  test_adjoint/test_fp_iteration.py
  test_adjoint/test_mesh_seq.py
  test_adjoint/test_utils.py
Labels: documentation, install

#170 Add type and field checks to `MeshSeq`
  demos/solid_body_rotation_split.py
  goalie/mesh_seq.py
  test/test_mesh_seq.py
  test_adjoint/examples/burgers.py
  test_adjoint/examples/point_discharge2d.py
  test_adjoint/examples/point_discharge3d.py
  test_adjoint/examples/steady_flow_past_cyl.py
  test_adjoint/test_mesh_seq.py
Labels: testing, refactor, clarity

#168 Remove `get_bcs` in `MeshSeq`
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  goalie/adjoint.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  test_adjoint/examples/point_discharge2d.py
  test_adjoint/examples/point_discharge3d.py
  test_adjoint/examples/steady_flow_past_cyl.py
  test_adjoint/test_adjoint.py
Labels: clarity

#184 Allow interpolating mixed functions to enriched spaces
  goalie/go_mesh_seq.py
Labels: bug

#187 185: Allow passing transfer kwargs
  goalie/mesh_seq.py
Labels: enhancement
