Repository mesh-adaptation/goalie, pull requests merged in 2024-02, with the labels that each got.

#108 107 mixed space adj project
  goalie/adjoint.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
Labels: bug

#101 Add simple ODE demo
  demos/ode.py
  goalie/__init__.py
  goalie/mesh_seq.py
  goalie/point_seq.py
  goalie/utility.py
Labels: documentation, enhancement

#114 Introduce `SolutionData` and `IndicatorData` classes
  goalie/adjoint.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  test/test_error_estimation.py
Labels: enhancement
