Repository mesh-adaptation/goalie, pull requests merged in 2024-11, with the labels that each got.

#221 Export function data to vtk or h5
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/solid_body_rotation.py
  goalie/function_data.py
  test/test_function_data.py
  test_adjoint/test_demos.py
Labels: enhancement

#227 Use `idx` kwarg in `CheckpointFile` when exporting
  goalie/function_data.py
Labels: enhancement

#231 Get `value_shape` from function spaces
  test_adjoint/test_mesh_seq.py
Labels: bug, PRIORITY

#233 Remove missed `get_form`
  goalie/point_seq.py
Labels: refactor

#237 Restructure tests
  .github/workflows/test_suite.yml
  Makefile
  goalie/mesh_seq.py
  test/Makefile
  test/adjoint/Makefile
  test/adjoint/conftest.py
  test/adjoint/examples/burgers.py
  test/adjoint/examples/mesh-with-hole.geo
  test/adjoint/examples/mesh-with-hole.msh
  test/adjoint/examples/point_discharge2d.py
  test/adjoint/examples/point_discharge3d.py
  test/adjoint/examples/steady_flow_past_cyl.py
  test/adjoint/test_adjoint.py
  test/adjoint/test_adjoint_mesh_seq.py
  test/adjoint/test_demos.py
  test/adjoint/test_fp_iteration.py
  test/adjoint/test_utils.py
  test/test_mesh_seq.py
  test_adjoint/conftest.py
Labels: testing

#164 Mixed steady/unsteady
  demos/mantle_convection.py
  goalie/function_data.py
  goalie/mesh_seq.py
Labels: bug, documentation
