Repository mesh-adaptation/goalie, pull requests merged in 2024-03, with the labels that each got.

#118 Always export final solution
  goalie/adjoint.py
  goalie/mesh_seq.py
  test_adjoint/test_adjoint.py
Labels: bug

#129 Avoid interpolation deprecation warning
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott_split.py
  demos/solid_body_rotation.py
  demos/solid_body_rotation_split.py
  goalie/__init__.py
  goalie/utility.py
  test/test_interpolation.py
  test/test_utility.py
  test_adjoint/examples/burgers.py
  test_adjoint/examples/steady_flow_past_cyl.py
Labels: bug

#131 VTK API update
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/solid_body_rotation.py
  demos/solid_body_rotation_split.py
  goalie/utility.py
  test/test_utility.py
  test_adjoint/test_adjoint.py
Labels: bug

#113 Disallow h-enrichment of shallow-copied meshes
  goalie/go_mesh_seq.py
  test_adjoint/test_mesh_seq.py
Labels: bug

#111 Introduce indexing and slicing of `TimePartition`
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/solid_body_rotation.py
  goalie/mesh_seq.py
  goalie/time_partition.py
  test/test_time_partition.py
  test_adjoint/examples/burgers.py
Labels: enhancement

#136 Fix time in plots
  goalie/plot.py
Labels: bug

#134 Purge typehints; mention type in docstrings
  goalie/adjoint.py
  goalie/error_estimation.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/interpolation.py
  goalie/log.py
  goalie/mesh_seq.py
  goalie/options.py
  goalie/point_seq.py
  goalie/time_partition.py
  goalie/utility.py
Labels: documentation

#139 Reinitialise output dictionaries before solving
  goalie/adjoint.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
Labels: bug

#116 Alternative data access methods for `FunctionData` and subclasses
  goalie/__init__.py
  goalie/adjoint.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  test/test_function_data.py
Labels: enhancement

#128 Parallel-safe mesh-to-mesh interpolation
  goalie/adjoint.py
  goalie/go_mesh_seq.py
  goalie/interpolation.py
  goalie/mesh_seq.py
  test/test_interpolation.py
Labels: enhancement, testing
