Repository mesh-adaptation/goalie, pull requests merged in 2024-05, with the labels that each got.

#190 Temporarily revert to project as the default transfer method
  goalie/mesh_seq.py
Labels: bug

#192 Minor ODE demo fix
  demos/ode.py
Labels: documentation

#191 #55 Update multiple fields in indicate_errors
  goalie/go_mesh_seq.py
  pyproject.toml
Labels: bug

#193 Enable B linting rules
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/solid_body_rotation.py
  goalie/adjoint.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  goalie/options.py
  goalie/time_partition.py
  pyproject.toml
  test/test_function_data.py
  test/test_utility.py
Labels: bug, testing

#199 Shorten demos during testing outside of original scripts
  demos/burgers-hessian.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/solid_body_rotation.py
  test_adjoint/test_demos.py
Labels: testing, clarity

#196 Automatically initialise fields and assign initial conditions
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/mesh_seq.py
  demos/ode.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  demos/time_partition.py
  goalie/adjoint.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  goalie/time_partition.py
  test/test_time_partition.py
  test_adjoint/examples/burgers.py
  test_adjoint/examples/point_discharge2d.py
  test_adjoint/examples/point_discharge3d.py
  test_adjoint/examples/steady_flow_past_cyl.py
  test_adjoint/test_adjoint.py
  test_adjoint/test_fp_iteration.py
  test_adjoint/test_utils.py
Labels: refactor, clarity

#194 Add `CITATION.cff`
  .github/workflows/test_suite.yml
  CITATION.cff
  Makefile
  pyproject.toml
Labels: documentation
