Repository mesh-adaptation/goalie, pull requests merged in 2024-12, with the labels that each got.

#112 Add time-dependent isotropic goal-oriented demo
  demos/burgers-goal_oriented.py
Labels: documentation

#247 Fix path to docs repo
  .github/workflows/test_suite.yml
Labels: bug, testing, PRIORITY

#243 Add method to interpolate data from one `FunctionData` object to another
  goalie/function_data.py
  test/test_function_data.py
Labels: enhancement

#253 Fix cache error in test suite
  test/conftest.py
Labels: bug, testing

#254 Update Makefile after restructuring tests
  Makefile
Labels: testing

#256 Match the order of export of ICs and sols
  goalie/function_data.py
Labels: bug

#271 Avoid polluting Goalie namespace
  demos/burgers-hessian.py
  demos/burgers_time_integrated.py
  goalie/__init__.py
  goalie/utility.py
Labels: bug
