Repository mesh-adaptation/goalie, pull requests merged in 2024-09, with the labels that each got.

#214 Use ghcr image in test suite
  .github/workflows/test_suite.yml
Labels: testing

#213 Update params in point discharge demo
  demos/point_discharge2d-goal_oriented.py
Labels: bug, documentation

#212 Compute error indicators after each subinterval
  goalie/adjoint.py
  goalie/go_mesh_seq.py
Labels: refactor

#197 Only run tests if .py files are changed in a commit
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
Labels: testing

#216 Separate out test workflows for changed files check vs. full test suite
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
  CITATION.cff
Labels: bug

#217 Fix changed-files pathing
  .github/workflows/test_suite.yml
Labels: bug

#218 Use reusable workflows
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
  Makefile
Labels: testing
