Repository mesh-adaptation/goalie, pull requests merged in 2025-04, with the labels that each got.

#300 Update $p$-refinement after moving to `Field` approach
  goalie/adjoint.py
  goalie/go_mesh_seq.py
  test/adjoint/test_adjoint_mesh_seq.py
Labels: refactor

#301 Introduce `get_element` and `get_function_space` methods to `Field` class
  demos/burgers-goal_oriented.py
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/mesh_seq.py
  demos/ode.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  demos/time_partition.py
  goalie/adjoint.py
  goalie/field.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  test/adjoint/test_adjoint.py
  test/adjoint/test_adjoint_mesh_seq.py
  test/adjoint/test_gradient.py
  test/adjoint/test_utils.py
  test/test_error_estimation.py
  test/test_field.py
  test/test_function_data.py
  test/test_mesh_seq.py
  test/test_metric.py
  test/test_parallel.py
  test/test_time_partition.py
Labels: refactor

#296 Drop `get_function_spaces`
  demos/burgers-goal_oriented.py
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/mantle_convection.py
  demos/mesh_seq.py
  demos/ode.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  demos/time_partition.py
  goalie/__init__.py
  goalie/adjoint.py
  goalie/field.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  goalie/point_seq.py
  test/adjoint/examples/burgers.py
  test/adjoint/examples/point_discharge2d.py
  test/adjoint/examples/point_discharge3d.py
  test/adjoint/examples/steady_flow_past_cyl.py
  test/adjoint/test_adjoint.py
  test/adjoint/test_adjoint_mesh_seq.py
  test/adjoint/test_gradient.py
  test/adjoint/test_utils.py
  test/test_error_estimation.py
  test/test_field.py
  test/test_function_data.py
  test/test_mesh_seq.py
  test/test_metric.py
  test/test_parallel.py
  test/test_time_partition.py
Labels: refactor

#294 Non-prognostic fields
  demos/burgers-goal_oriented.py
  demos/burgers-hessian.py
  demos/burgers.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/mantle_convection.py
  demos/mesh_seq.py
  demos/ode.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d-hessian.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  demos/time_partition.py
  goalie/__init__.py
  goalie/adjoint.py
  goalie/field.py
  goalie/function_data.py
  goalie/go_mesh_seq.py
  goalie/mesh_seq.py
  goalie/point_seq.py
  goalie/time_partition.py
  test/adjoint/Makefile
  test/adjoint/examples/burgers.py
  test/adjoint/examples/point_discharge2d.py
  test/adjoint/examples/point_discharge3d.py
  test/adjoint/examples/steady_flow_past_cyl.py
  test/adjoint/test_adjoint.py
  test/adjoint/test_adjoint_mesh_seq.py
  test/adjoint/test_gradient.py
  test/adjoint/test_utils.py
  test/test_error_estimation.py
  test/test_field.py
  test/test_function_data.py
  test/test_mesh_seq.py
  test/test_metric.py
  test/test_parallel.py
  test/test_time_partition.py
Labels: enhancement

#303 Minor `Field` docstring fix
  goalie/field.py
Labels: clarity

#307 Drop `goalie_adjoint`
  demos/burgers-goal_oriented.py
  demos/burgers1.py
  demos/burgers2.py
  demos/burgers_ee.py
  demos/burgers_oo.py
  demos/burgers_time_integrated.py
  demos/gray_scott.py
  demos/gray_scott_split.py
  demos/point_discharge2d-goal_oriented.py
  demos/point_discharge2d.py
  demos/solid_body_rotation.py
  goalie/__init__.py
  goalie_adjoint/__init__.py
  pyproject.toml
Labels: refactor
